# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mountains and Milkshakes
email: ruby@mountainsandmilkshakes.com
description: > # this means to ignore newlines until "baseurl:"
  We enjoy hiking in the mountains and drinking milkshakes afterward.
  Come for the blog, stay for the pictures of our dog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mountainsandmilkshakes.com" # the base hostname & protocol for your site
# twitter_username: i_shot_first

# Build settings
markdown: kramdown
